### ISSUE TITLE
Solana Metrics for Accounts DB Plugin

### ISSUE THREAD

**Issue by kespinola** [holaplex/solana-indexer#170]
### Goal
Metrics on accounts db plugin processing are sent to solana metrics.

### Requirements
- Add solana metrics crate to the plugin.
- Track the processing time of an account being sent to rabbitmq.
- Send timing metrics to Solana metrics.

**Comment by dandlezzz** [comment]
see https://github.com/rpcpool/solana-accountsdb-sqs
