### ISSUE TITLE
Filter NFTs by Token Owner

### ISSUE THREAD

**Issue by dandlezzz** [holaplex/solana-indexer#196]
## Goal

The nfts root query can accept a further filter of `owners: ["{address}"]` to find which nfts are owned by a user for a collection.

```graphql
nfts(creators: ["{creator}"], owners: ["{owner}"]) {
  address
  details {
  ..
 }
}
```

This requires knowing the current authority over the spl mint token for the nft.

**Comment by kespinola** [comment]
done. follows above api.
