### ISSUE TITLE
Holaplex Asset Proxy for Image Fields

### ISSUE THREAD

**Issue by kespinola** [holaplex/solana-indexer#207]
### Goal

Faster image rendering!

When users request an image type field from the graphql server it should return a `assets.holaplex.com` which uses are image optimizer to resize and cache images.

### Requirements

- Image fields accept size parameter that match supported resize options of assets proxy.
```graphql
nft(address: "address") {
  name
  image(size: "500")
}
```
- Regex match the image url stored in the DB with its assets.holaplex.com equivalent.
- Return field value of the assets proxy url including its size query paramater.

**Comment by dandlezzz** [comment]
Does juniper support field parameters? 
`image(size: "500")`

**Comment by kespinola** [comment]
done.
